datasets:
  root: ../data/WikiSimple-translated
  prepare: False
  split:
    train: train
    valid: valid

parameters:
  batch_size: 16
  device: cuda
  tokenizer: ../data/WikiSimple-translated/tokenizer-wikisimple.json
  embedding_size: 512
  num_heads: 8
  num_encoder_layers: 3
  num_decoder_layers: 3
  dropout: 0.10
  max_len: 60
  forward_expansion: 2048
  activation: gelu
  optimizer:
    lr: 3e-4
  scheduler:
    ReduceLROnPlateau:
      factor: 0.1
      patience: 10
      verbose: True

trainer:
  epochs: 5
  verbose_step: 200
  max_length: 50
  valid_sentence: Боуэлл был впервые избран в Палату общин в 1867 году как консерватор за верховую езду в Северном Гастингсе, Онтарио.
  model_dir: models/default_transformer
  load_checkpoint: False